### ISSUE TITLE
`run_toi` error on cluster:  `import exoplanet --> Could not import 'mkl'` 

### ISSUE THREAD

**Issue by avivajpeyi** [dfm/tess-atlas#109]
```python
import exoplanet as xo
...
---->  import aesara_theano_fallback.tensor as tt
...
--> from theano.tensor.blas_headers import blas_header_text, blas_header_version
...
RuntimeError:
Could not import 'mkl'.  If you are using conda, update the numpy
packages to the latest build otherwise, set MKL_THREADING_LAYER=GNU in
your environment for MKL 2018.

If you have MKL 2017 install and are not in a conda environment you
can set the Theano flag blas__check_openmp to False.  Be warned that if
you set this flag and don't set the appropriate environment or make
sure you have the right version you *will* get wrong results.
```

<details>
<summary>Full trace:</summary>

```python
2021-10-06 14:00:13,160 - TESS-ATLAS-RUNNER - INFO - Executing /fred/oz200/avajpeyi/projects/atlas_runs/notebooks/0.2.1.dev47+gb8ffc4a/toi_103.ipynb
2021-10-06 14:00:23,119 - TESS-ATLAS-RUNNER - ERROR - Preprocessing /fred/oz200/avajpeyi/projects/atlas_runs/notebooks/0.2.1.dev47+gb8ffc4a/toi_103.ipynb failed:

 An error occurred while executing the following cell:
------------------
import logging
import os

import exoplanet as xo
import numpy as np
import pandas as pd
import pymc3 as pm
import pymc3_ext as pmx
import aesara_theano_fallback.tensor as tt
from aesara_theano_fallback import aesara as theano

from celerite2.theano import GaussianProcess, terms
from pymc3.sampling import MultiTrace

from tess_atlas.data import TICEntry
from tess_atlas.analysis.eccenticity_reweighting import (
    calculate_eccentricity_weights,
)

from tess_atlas.utils import notebook_initalisations
from tess_atlas.utils import NOTEBOOK_LOGGER_NAME

notebook_initalisations()
logger = logging.getLogger(NOTEBOOK_LOGGER_NAME)
------------------

---------------------------------------------------------------------------
NoSectionError                            Traceback (most recent call last)
/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/theano/configparser.py in fetch_val_for_key(self, key, delete_key)
    237             try:
--> 238                 return self._theano_cfg.get(section, option)
    239             except InterpolationError:

/apps/skylake/software/Python/3.7.4-gni-2020.0/lib/python3.7/configparser.py in get(self, section, option, raw, vars, fallback)
    779         try:
--> 780             d = self._unify_values(section, vars)
    781         except NoSectionError:

/apps/skylake/software/Python/3.7.4-gni-2020.0/lib/python3.7/configparser.py in _unify_values(self, section, vars)
   1145             if section != self.default_section:
-> 1146                 raise NoSectionError(section) from None
   1147         # Update with the entry specific variables

NoSectionError: No section: 'blas'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/theano/configparser.py in __get__(self, cls, type_, delete_key)
    353             try:
--> 354                 val_str = cls.fetch_val_for_key(self.name, delete_key=delete_key)
    355                 self.is_default = False

/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/theano/configparser.py in fetch_val_for_key(self, key, delete_key)
    241         except (NoOptionError, NoSectionError):
--> 242             raise KeyError(key)
    243

KeyError: 'blas__ldflags'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/theano/link/c/cmodule.py in check_mkl_openmp()
   2580     try:
-> 2581         import mkl
   2582

ModuleNotFoundError: No module named 'mkl'

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_250384/210243958.py in <module>
      2 import os
      3
----> 4 import exoplanet as xo
      5 import numpy as np
      6 import pandas as pd

/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/exoplanet/__init__.py in <module>
      3 __all__ = ["__version__", "distributions", "orbits", "interp"]
      4
----> 5 from . import distributions, interp, orbits
      6 from .citations import CITATIONS
      7 from .distributions import *  # NOQA

/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/exoplanet/distributions/__init__.py in <module>
      3 __all__ = ["QuadLimbDark", "ImpactParameter", "eccentricity"]
      4
----> 5 from . import eccentricity
      6 from .physical import ImpactParameter, QuadLimbDark

/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/exoplanet/distributions/eccentricity.py in <module>
      3 __all__ = ["kipping13", "vaneylen19"]
      4
----> 5 import aesara_theano_fallback.tensor as tt
      6 import numpy as np
      7 import pymc3 as pm

/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/aesara_theano_fallback/__init__.py in <module>
     11 ]
     12
---> 13 from . import graph, tensor
     14 from .compat import USE_AESARA, aesara, sparse, change_flags, ifelse
     15 from .aesara_theano_fallback_version import version as __version__  # noqa

/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/aesara_theano_fallback/graph.py in <module>
      1 # -*- coding: utf-8 -*-
      2
----> 3 from .compat import USE_AESARA
      4
      5 if USE_AESARA:

/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/aesara_theano_fallback/compat.py in <module>
     18 if aesara is None or not USE_AESARA:
     19     try:
---> 20         import theano.graph
     21
     22     except ImportError:

/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/theano/__init__.py in <module>
     81 __api_version__ = 1
     82
---> 83 from theano import scalar, tensor
     84 from theano.compile import (
     85     In,

/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/theano/tensor/__init__.py in <module>
     18     verify_grad,
     19 )
---> 20 from theano.tensor import nnet  # used for softmax, sigmoid, etc.
     21 from theano.tensor import sharedvar  # adds shared-variable constructors
     22 from theano.tensor import (

/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/theano/tensor/nnet/__init__.py in <module>
      1 import warnings
      2
----> 3 from . import opt
      4 from .abstract_conv import conv2d as abstract_conv2d
      5 from .abstract_conv import conv2d_grad_wrt_inputs, conv3d, separable_conv2d

/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/theano/tensor/nnet/opt.py in <module>
     30
     31 # Cpu implementation
---> 32 from theano.tensor.nnet.conv import ConvOp, conv2d
     33 from theano.tensor.nnet.corr import CorrMM, CorrMM_gradInputs, CorrMM_gradWeights
     34 from theano.tensor.nnet.corr3d import Corr3dMM, Corr3dMMGradInputs, Corr3dMMGradWeights

/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/theano/tensor/nnet/conv.py in <module>
     18 from theano.graph.basic import Apply
     19 from theano.graph.op import OpenMPOp
---> 20 from theano.tensor import blas
     21 from theano.tensor.basic import (
     22     NotScalarConstantError,

/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/theano/tensor/blas.py in <module>
    161 from theano.scalar import bool as bool_t
    162 from theano.tensor import basic as tt
--> 163 from theano.tensor.blas_headers import blas_header_text, blas_header_version
    164 from theano.tensor.opt import in2out, local_dimshuffle_lift
    165 from theano.tensor.type import values_eq_approx_remove_inf_nan

/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/theano/tensor/blas_headers.py in <module>
   1014
   1015
-> 1016 if not config.blas__ldflags:
   1017     _logger.warning("Using NumPy C-API based implementation for BLAS functions.")
   1018

/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/theano/configparser.py in __get__(self, cls, type_, delete_key)
    356             except KeyError:
    357                 if callable(self.default):
--> 358                     val_str = self.default()
    359                 else:
    360                     val_str = self.default

/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/theano/link/c/cmodule.py in default_blas_ldflags()
   2793         if res:
   2794             if "mkl" in res:
-> 2795                 check_mkl_openmp()
   2796             return res
   2797

/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/theano/link/c/cmodule.py in check_mkl_openmp()
   2600 you set this flag and don't set the appropriate environment or make
   2601 sure you have the right version you *will* get wrong results.
-> 2602 """
   2603         )
   2604

RuntimeError:
Could not import 'mkl'.  If you are using conda, update the numpy
packages to the latest build otherwise, set MKL_THREADING_LAYER=GNU in
your environment for MKL 2018.

If you have MKL 2017 install and are not in a conda environment you
can set the Theano flag blas__check_openmp to False.  Be warned that if
you set this flag and don't set the appropriate environment or make
sure you have the right version you *will* get wrong results.

RuntimeError:
Could not import 'mkl'.  If you are using conda, update the numpy
packages to the latest build otherwise, set MKL_THREADING_LAYER=GNU in
your environment for MKL 2018.

If you have MKL 2017 install and are not in a conda environment you
can set the Theano flag blas__check_openmp to False.  Be warned that if
you set this flag and don't set the appropriate environment or make
sure you have the right version you *will* get wrong results.


2021-10-06 14:00:23,254 - TESS-ATLAS-RUNNER - INFO - TOI 103 execution passed: False (10.33s)

```
</details>

**Comment by avivajpeyi** [comment]
Same error 
https://stackoverflow.com/questions/49048734/runtimeerror-to-use-mkl-2018-with-theano-you-must-set-mkl-threading-layer-gnu

**Comment by avivajpeyi** [comment]
https://github.com/Theano/Theano/issues/6568
suggests setting `os.environ["MKL_THREADING_LAYER"] = "GNU"`

```python
>>> import os
>>> os.environ["MKL_THREADING_LAYER"] = "GNU"
>>>
>>> import exoplanet
Traceback (most recent call last):
  File "/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/exoplanet/__init__.py", line 5, in <module>
    from . import distributions, interp, orbits
  ...
  File "/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/theano/tensor/nnet/nnet.py", line 32, in <module>
    from theano.tensor.nnet.sigm import sigmoid, softplus
  File "/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/theano/tensor/nnet/sigm.py", line 275, in <module>
    theano.compile.optdb['uncanonicalize'].register("local_ultra_fast_sigmoid",
AttributeError: module 'theano' has no attribute 'compile'
```

**Comment by avivajpeyi** [comment]
Weird that this doesnt show up on my local machine:

<details>
<summary>local pip-freeze:</summary>

> aesara-theano-fallback==0.0.4
> alabaster==0.7.12
> anyio==3.3.2
> appnope==0.1.2
> argon2-cffi==21.1.0
> arviz==0.11.4
> astropy==4.3.1
> astroquery==0.4.3
> attrs==20.3.0
> autograd==1.3
> Babel==2.9.1
> backcall==0.2.0
> backports.entry-points-selectable==1.1.0
> beautifulsoup4==4.10.0
> black==21.9b0
> bleach==4.1.0
> bokeh==2.4.0
> cachetools==4.2.4
> celerite2==0.2.0
> certifi==2021.5.30
> cffi==1.14.6
> cfgv==3.3.1
> cftime==1.5.1
> charset-normalizer==2.0.6
> click==7.1.2
> colorama==0.4.4
> corner==2.2.1
> cycler==0.10.0
> debugpy==1.5.0
> decorator==5.1.0
> defusedxml==0.7.1
> dill==0.3.4
> distlib==0.3.3
> docutils==0.16
> entrypoints==0.3
> exoplanet==0.5.1
> exoplanet-core==0.1.2
> fastprogress==1.0.0
> fbpca==1.0
> filelock==3.3.0
> flake8==3.9.2
> future==0.18.2
> gitdb==4.0.7
> GitPython==3.1.24
> greenlet==1.1.2
> html5lib==1.1
> identify==2.3.0
> idna==3.2
> imagesize==1.2.0
> importlib-metadata==4.8.1
> iniconfig==1.1.1
> ipykernel==6.4.1
> ipython==7.28.0
> ipython-genutils==0.2.0
> ipywidgets==7.6.5
> isort==5.9.3
> jedi==0.18.0
> Jinja2==3.0.2
> joblib==1.0.1
> jsonschema==4.0.1
> jupyter==1.0.0
> jupyter-book==0.11.3
> jupyter-cache==0.4.3
> jupyter-client==6.1.12
> jupyter-console==6.4.0
> jupyter-core==4.8.1
> jupyter-server==1.11.1
> jupyter-server-mathjax==0.2.3
> jupyter-sphinx==0.3.2
> jupyterlab-widgets==1.0.2
> jupytext==1.10.3
> kaleido==0.2.1
> keyring==23.2.1
> kiwisolver==1.3.2
> latexcodec==2.0.1
> lightkurve==2.0.11
> linkify-it-py==1.0.1
> markdown-it-py==0.6.2
> MarkupSafe==2.0.1
> matplotlib==3.4.3
> matplotlib-inline==0.1.3
> mccabe==0.6.1
> mdit-py-plugins==0.2.6
> memoization==0.4.0
> mimeparse==0.1.3
> mistune==0.8.4
> mypy-extensions==0.4.3
> myst-nb==0.12.3
> myst-parser==0.13.7
> nbclient==0.5.4
> nbconvert==5.6.1
> nbdime==3.1.0
> nbformat==5.1.3
> nest-asyncio==1.5.1
> netCDF4==1.5.7
> nodeenv==1.6.0
> notebook==6.4.4
> numpy==1.21.2
> oktopus==0.1.2
> packaging==21.0
> pandas==1.3.3
> pandocfilters==1.5.0
> parso==0.8.2
> pathspec==0.9.0
> patsy==0.5.2
> pexpect==4.8.0
> pickleshare==0.7.5
> Pillow==8.3.2
> platformdirs==2.4.0
> plotly==5.3.1
> pluggy==1.0.0
> pre-commit==2.15.0
> prometheus-client==0.11.0
> prompt-toolkit==3.0.20
> ptyprocess==0.7.0
> py==1.10.0
> pybtex==0.24.0
> pybtex-docutils==1.0.1
> pycodestyle==2.7.0
> pycparser==2.20
> pydata-sphinx-theme==0.6.3
> pyerfa==2.0.0
> pyflakes==2.3.1
> Pygments==2.10.0
> pymc3==3.11.4
> pymc3-ext==0.1.0
> pyparsing==2.4.7
> pyrsistent==0.18.0
> pytest==6.2.5
> python-dateutil==2.8.2
> pytz==2021.3
> pyvo==1.1
> PyYAML==5.4.1
> pyzmq==22.3.0
> qtconsole==5.1.1
> QtPy==1.11.2
> regex==2021.9.30
> requests==2.26.0
> requests-unixsocket==0.2.0
> scikit-learn==1.0
> scipy==1.7.1
> seaborn==0.11.2
> semver==2.13.0
> Send2Trash==1.8.0
> six==1.16.0
> smmap==4.0.0
> sniffio==1.2.0
> snowballstemmer==2.1.0
> soupsieve==2.2.1
> Sphinx==3.5.4
> sphinx-book-theme==0.1.5
> sphinx-comments==0.0.3
> sphinx-copybutton==0.4.0
> sphinx-external-toc==0.2.3
> sphinx-jupyterbook-latex==0.4.4
> sphinx-multitoc-numbering==0.1.3
> sphinx-panels==0.5.2
> sphinx-thebe==0.0.10
> sphinx-togglebutton==0.2.3
> sphinxcontrib-applehelp==1.0.2
> sphinxcontrib-bibtex==2.2.1
> sphinxcontrib-devhelp==1.0.2
> sphinxcontrib-htmlhelp==2.0.0
> sphinxcontrib-jsmath==1.0.1
> sphinxcontrib-qthelp==1.0.3
> sphinxcontrib-serializinghtml==1.1.5
> SQLAlchemy==1.4.25
> tenacity==8.0.1
> terminado==0.12.1
> -e git+...=tess_atlas
> testbook==0.4.2
> testpath==0.5.0
> Theano-PyMC==1.1.2
> threadpoolctl==3.0.0
> toml==0.10.2
> tomli==1.2.1
> tornado==6.1
> tqdm==4.62.3
> traitlets==5.1.0
> typing-extensions==3.10.0.2
> uc-micro-py==1.0.1
> uncertainties==3.1.6
> urllib3==1.26.7
> virtualenv==20.8.1
> wcwidth==0.2.5
> webencodings==0.5.1
> websocket-client==1.2.1
> widgetsnbextension==3.5.1
> xarray==0.19.0
> zipp==3.6.0


</details>



<details>
<summary>Cluster pip-freeze:</summary>

> aesara-theano-fallback==0.0.4
> alabaster==0.7.12
> anyio==3.3.2
> argcomplete==1.12.3
> argon2-cffi==21.1.0
> arviz==0.11.4
> astropy==4.3.1
> astroquery==0.4.3
> attrs==20.3.0
> autograd==1.3
> Babel==2.9.1
> backcall==0.2.0
> backports.entry-points-selectable==1.1.0
> beautifulsoup4==4.10.0
> black==21.9b0
> bleach==4.1.0
> bokeh==2.4.0
> cached-property==1.5.2
> cachetools==4.2.4
> celerite2==0.2.0
> certifi==2021.5.30
> cffi==1.14.6
> cfgv==3.3.1
> cftime==1.5.1
> charset-normalizer==2.0.6
> click==7.1.2
> colorama==0.4.4
> corner==2.2.1
> cryptography==35.0.0
> cycler==0.10.0
> Cython==0.29.21
> debugpy==1.5.0
> decorator==5.1.0
> defusedxml==0.7.1
> dill==0.3.4
> distlib==0.3.3
> docutils==0.16
> entrypoints==0.3
> exoplanet==0.5.1
> exoplanet-core==0.1.2
> fastprogress==1.0.0
> fbpca==1.0
> filelock==3.3.0
> flake8==3.9.2
> future==0.18.2
> gitdb==4.0.7
> GitPython==3.1.24
> greenlet==1.1.2
> h5py==3.2.1
> html5lib==1.1
> identify==2.3.0
> idna==3.2
> imagesize==1.2.0
> importlib-metadata==4.8.1
> importlib-resources==5.2.2
> iniconfig==1.1.1
> intel-openmp==2021.4.0
> ipykernel==6.4.1
> ipython==7.28.0
> ipython-genutils==0.2.0
> ipywidgets==7.6.5
> isort==5.9.3
> jedi==0.18.0
> jeepney==0.7.1
> Jinja2==3.0.2
> joblib==1.0.1
> jsonschema==4.0.1
> jupyter==1.0.0
> jupyter-book==0.11.3
> jupyter-cache==0.4.3
> jupyter-client==6.1.12
> jupyter-console==6.4.0
> jupyter-core==4.8.1
> jupyter-server==1.11.1
> jupyter-server-mathjax==0.2.3
> jupyter-sphinx==0.3.2
> jupyterlab-pygments==0.1.2
> jupyterlab-widgets==1.0.2
> jupytext==1.10.3
> kaleido==0.2.1
> keyring==23.2.1
> kiwisolver==1.3.2
> latexcodec==2.0.1
> lightkurve==2.0.11
> linkify-it-py==1.0.1
> markdown-it-py==0.6.2
> MarkupSafe==2.0.1
> matplotlib==3.4.3
> matplotlib-inline==0.1.3
> mccabe==0.6.1
> mdit-py-plugins==0.2.6
> memoization==0.4.0
> mimeparse==0.1.3
> mistune==0.8.4
> mkl==2021.4.0
> mpi4py==3.0.3
> mypy-extensions==0.4.3
> myst-nb==0.12.3
> myst-parser==0.13.7
> nbclient==0.5.4
> nbconvert==5.6.1
> nbdime==3.1.0
> nbformat==5.1.3
> nest-asyncio==1.5.1
> netCDF4==1.5.7
> nodeenv==1.6.0
> notebook==6.4.4
> numpy==1.19.2
> oktopus==0.1.2
> packaging==21.0
> pandas==1.3.3
> pandocfilters==1.5.0
> parso==0.8.2
> pathspec==0.9.0
> patsy==0.5.2
> pexpect==4.8.0
> pickleshare==0.7.5
> Pillow==8.3.2
> platformdirs==2.4.0
> plotly==5.3.1
> pluggy==1.0.0
> pre-commit==2.15.0
> prometheus-client==0.11.0
> prompt-toolkit==3.0.20
> ptyprocess==0.7.0
> py==1.10.0
> pybind11==2.5.0
> pybtex==0.24.0
> pybtex-docutils==1.0.1
> pycodestyle==2.7.0
> pycparser==2.20
> pydata-sphinx-theme==0.6.3
> pyerfa==2.0.0
> pyflakes==2.3.1
> Pygments==2.10.0
> pymc3==3.11.4
> pymc3-ext==0.1.0
> pyparsing==2.4.7
> pyrsistent==0.18.0
> pytest==6.2.5
> python-dateutil==2.8.2
> pytz==2021.3
> pyvo==1.1
> PyYAML==5.4.1
> pyzmq==22.3.0
> qtconsole==5.1.1
> QtPy==1.11.2
> regex==2021.9.30
> requests==2.26.0
> requests-unixsocket==0.2.0
> scikit-learn==1.0
> scipy==1.6.0
> seaborn==0.11.2
> SecretStorage==3.3.1
> semver==2.13.0
> Send2Trash==1.8.0
> six==1.16.0
> smmap==4.0.0
> sniffio==1.2.0
> snowballstemmer==2.1.0
> soupsieve==2.2.1
> Sphinx==3.5.4
> sphinx-book-theme==0.1.5
> sphinx-comments==0.0.3
> sphinx-copybutton==0.4.0
> sphinx-external-toc==0.2.3
> sphinx-jupyterbook-latex==0.4.3
> sphinx-multitoc-numbering==0.1.3
> sphinx-panels==0.5.2
> sphinx-thebe==0.0.10
> sphinx-togglebutton==0.2.3
> sphinxcontrib-applehelp==1.0.2
> sphinxcontrib-bibtex==2.2.1
> sphinxcontrib-devhelp==1.0.2
> sphinxcontrib-htmlhelp==2.0.0
> sphinxcontrib-jsmath==1.0.1
> sphinxcontrib-qthelp==1.0.3
> sphinxcontrib-serializinghtml==1.1.5
> SQLAlchemy==1.4.25
> tbb==2021.4.0
> tenacity==8.0.1
> terminado==0.12.1
> -e git+...tess_atlas
> testbook==0.4.2
> testpath==0.5.0
> Theano==1.0.5
> Theano-PyMC==1.1.2
> threadpoolctl==3.0.0
> toml==0.10.2
> tomli==1.2.1
> tornado==6.1
> tqdm==4.62.3
> traitlets==5.1.0
> typed-ast==1.4.3
> typing-extensions==3.10.0.2
> uc-micro-py==1.0.1
> uncertainties==3.1.6
> urllib3==1.26.7
> virtualenv==20.8.1
> wcwidth==0.2.5
> webencodings==0.5.1
> websocket-client==1.2.1
> widgetsnbextension==3.5.1
> xarray==0.19.0
> zipp==3.6.0


</details>

**Comment by avivajpeyi** [comment]
On getting rid of the `module load`-ed numpy and scipy, and updating to match my local machine: 
```diff
< argcomplete==1.12.3
---
> appnope==0.1.2
28d27
< cryptography==35.0.0
30d28
< Cython==0.29.21
53d50
< importlib-resources==5.2.2
55d51
< intel-openmp==2021.4.0
62d57
< jeepney==0.7.1
75d69
< jupyterlab-pygments==0.1.2
93d86
< mkl==2021.4.0
124d116
< pybind11==2.5.0
151d142
< SecretStorage==3.3.1
164c155
< sphinx-jupyterbook-latex==0.4.3
---
> sphinx-jupyterbook-latex==0.4.4
177d167
< tbb==2021.4.0

``` 

I get a new error: 
```python
>>> import exoplanet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/exoplanet/__init__.py", line 5, in <module>
    from . import distributions, interp, orbits
  File "/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/exoplanet/distributions/__init__.py", line 5, in <module>
    from . import eccentricity
  File "/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/exoplanet/distributions/eccentricity.py", line 5, in <module>
    import aesara_theano_fallback.tensor as tt
  File "/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/aesara_theano_fallback/__init__.py", line 13, in <module>
    from . import graph, tensor
  File "/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/aesara_theano_fallback/graph.py", line 3, in <module>
    from .compat import USE_AESARA
  File "/fred/oz200/avajpeyi/envs/tess/lib/python3.7/site-packages/aesara_theano_fallback/compat.py", line 34, in <module>
    from theano import sparse
ImportError: cannot import name 'sparse' from 'theano' (unknown location)
>>>
```

**Comment by avivajpeyi** [comment]
Tried again, this time with a different module-loaded python (i think the previous had numpy loaded in!) 
```python
>>> import exoplanet
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
>>>
```

HUZZA!! 🥳  just a warning -- at least things aren't breaking! 😀

**Comment by avivajpeyi** [comment]
Lol this is now fixed, but along with it comes a new error: 
https://github.com/dfm/tess-atlas/issues/110
